SCREEN_WIDTH = 640#1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5

BACKGROUND_IMAGE = "images/space.png"
SAVE_FILE = "data/data.pickle"
FONT_FILE = "fonts/Rogbold-3llGM.otf"

LASER_SOUND_FILE = "sounds/laser1.ogg"
EXPLOSION_L_SOUND_FILE = "sounds/explosion3.ogg"
EXPLOSION_S_SOUND_FILE = "sounds/explosion2.ogg"
ENGINE_SOUND_FILE = "sounds/engine1.wav"
SHIP_EXPLOSION = "sounds/explosion6.ogg"

ENABLE_SOUNDS = False

HOST = '0.0.0.0' 
CLIENT_HOST = '192.168.0.100'
#'192.168.0.100' 
#'172.30.75.51' 
#'127.0.0.1'
PORT = 65432

GET_ACTION = 0
DESTROY_ACTION = 1

IN_MENU = 0
IN_SINGLEPLAYER_GAME = 1
IN_MULTIPLAYER_MENU = 2
IN_MULTIPLAYER_GAME = 3

MAX_CONNECTIONS = 2